version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Easy"
    cmds:
      - protoc -I proto -I /home/srcgod/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v1.0.4 proto/*.proto --go_out=./gen/profile --go_opt=paths=source_relative --go-grpc_out=./gen/profile --go-grpc_opt=paths=source_relative --validate_out="lang=go:./gen/profile"
